### PR TITLE
Basic UI design & Functionalities

### PR DESCRIPTION
**Pull request by jmonto55**
This Pull Request includes all the steps followed in order to develop the first part of the [Awesome Books Project](https://github.com/microverseinc/curriculum-javascript/blob/main/books/m1_plain_js_objects_v1_1.md), including:

- Basic UI design with plain HTML.
- Creation of an array that keeps the list of books.
- Functionality to add new books.
- Functionality to remove any specific book.
- Dynamically displaying the book list at the top part of the page.
- All data is preserved using LocalStorage.
- All functionalities were developed using plain JavaScript.

### CODE REVIEW

**Review by Reem-lab — COMMENTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that dpesn't have a descriptive PR so kindly add some details in your PR to explain what you did in this milestone specificly 🔥💯💯 and kindly apply the readme template by adding the project information instead of the placeholders ✅🔥♻

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Davidosky007 — COMMENTED** [review]
Hi @jmonto55 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a script in the package.json file which is used to run the app and also add setup instructions on your readme file so that visitors can know how to properly install and run your project 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jmonto55** [comment]
Hello 
[@Davidosky](https://microverse-students.slack.com/team/U016SV2LQ48)
, I wanted to reach you because I don't understand what you mean when you say that my project "doesn't have a script in the package.json file which is used to run the app and also add setup instructions on your readme file so that visitors can know how to properly install and run your project", I am currently on block 2 week 1 and I have not learned how to modify package.json files yet, those files are there because they were installed automatically while installing Linters and npm but I did not modify anything inside them, also while reviewing the project requirements I don't see that we needed to install any script inside the package.json file, could you please kindly explain me why are you asking for this requirement?

**Review by youmari — APPROVED** [review]
# Project Approved :trophy: :tada: 🟢 

Hi @jmonto55 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
